name: Infinite Restream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  actions: write

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Stream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x restream.sh
          ./restream.sh &
          
          # رفع كل 30 ثانية بدل دقيقتين (أسرع بكثير)
          while true; do
            sleep 30
            git config --global user.name "StreamBot"
            git config --global user.email "bot@github.com"
            git add hls/
            git commit -m "Live Update $(date +%H:%M:%S)" || true
            git push origin main || true
          done
